### ISSUE TITLE
Routes and views

### ISSUE THREAD

**Issue by CharlesNepote** [bi-tm/express-nedb-rest#12]
Maybe it's possible with Express but I don't know how to do that.

I would like to have particular views of the database based on the url. Example: see all the records but without the technical values such as `_id` and `createdAt` and `updatedAt`.

Other case: see and query all the records with { "status": "draft" } based on the url `http://127.0.0.1:8100/collection/draft/`. Example: `http://127.0.0.1:8100/collection/draft?$filter=$author $eq John`.

Maybe it's already possible and just a matter of documentation.

**Comment by bi-tm** [comment]
Hello Charles,
i will add an additional query parameter $select (as it is used in odata services). You'll can define the fieldnames, you want to get in the result set. i.E :
`http://127.0.0.1:8100/collection?$filter=author $eq John $and status $eq draft&$select=drafturi,createdAt `
will return all documents fitting the filter criteria, but only the attributes drafturi and createdAt are included:
` [{ "drafturi":"http://127.0.0.1:8100/test/1491467983925","createdAt"= 2017-04-27T21:45:00Z}]`

Would this solve your issue?
I hope to find some time for it this weekend.
Kindly
Torsten

**Comment by CharlesNepote** [comment]
Hi Torsten,
Your solution will solve the issue #13 (very good!) but not the current one. What I want is to provide raw documents with clean URL.

```http://127.0.0.1:8100/collection?$filter=author $eq John $and status $eq draft&$select=drafturi,createdAt``` is long and complex URL. I would prefer to have something like:

```
var restApi = expressNedbRest();
restApi.addDatastore('schemas', datastore);
restAPI.addView('raw_draft', '$filter=status $eq draft');
// http://localhost/path/schemas/raw_draft/$filter=author $eq John
// http://localhost/path/schemas/raw_draft/1273678636
```
or something like:
```
app.use("/raw", nedbRest.filter('$filter=status $eq draft&$select=drafturi,createdAt');
// With working URL:
// http://localhost/raw_draft/12454636868
// http://localhost/raw_draft/$filter=author $eq John
```
Do you understand? maybe I'm unclear...
May be it's just a matter of URL rewriting with Express but I don't know how to do that...

Best, Charles.

**Comment by CharlesNepote** [comment]
Hi Torsten,

I'm investigating a way to have clean urls but it doesn't work... In my example below, the URL `http://localhost/draft/2017-04-12T13:59:49.953Z` should provides the result of `http://localhost/rest/schemas?$filter=status $eq draft $and createdAt $eq 2017-04-12T13:59:49.953Z` but it returns all records of the database...
```javascript
// [...]
// URL rewriting
app.get('/draft/*', function(req, res, next) {
  // /draft/202017-04-12T13:59:49.953Z
  var regexp = new RegExp('^/draft/(.*)$', "g");                // build regexp
  req.url = req.url.replace(regexp, '/rest/schemas?$filter=status $eq draft $and createdAt $eq $1');
  console.log('http://localhost' + req.url);
  next();
});

// ---------- create rest api router and connect it to datastore
var restApi = expressNedbRest();
restApi.addDatastore('schemas', datastore);

// setup express server to serve rest service
app.use('/rest', restApi);

// [...]
```

Any idea of what's wrong?

Best regards,
Charles.

**Comment by bi-tm** [comment]
Hello Charles,
you are rewriting `req.url`, but the filter is in `req.query.$filter`. Perhaps it will work, if you update `req.query.$filter` also.
Best Regards
Torsten

**Comment by CharlesNepote** [comment]
Thanks Torsten, it worked! (see below). Would it be interesting to add a "tips" section in the documentation to let people see examples of interaction between Express and Express-Nedb-Rest?

I will also build an example combining URL rewriting and $filter in the URL, such as `/draft?$filter=author $eq John Doe`.

```javascript
// /draft/202017-04-12T13:59:49.953Z is a clean URL to access an existing draft document
app.get('/draft/:id', function(req, res, next) {
  // /draft/202017-04-12T13:59:49.953Z
  req.url = encodeURI(
    config.apiPath + '/' + config.datastore +
    '?$filter=status $eq draft $and createdAt $eq '+ req.params.id);
  req.query.$filter = 'status $eq draft $and createdAt $eq ' + req.params.id;
  console.log('http://localhost:' + config.port + req.url);
  next();
});

// /draft/ is a URL providing all documents with "status": "draft"
app.get('/draft/', function(req, res, next) {
  req.url = encodeURI(
    config.apiPath + '/' + config.datastore +
    '?$filter=status $eq draft');
  req.query.$filter = 'status $eq draft';
  console.log('http://localhost:' + config.port + req.url);
  next();
});

// ---------- create rest api router and connect it to datastore
var restApi = expressNedbRest();
restApi.addDatastore(config.datastore, datastore);

// setup express server to serve rest service
app.use(config.apiPath, restApi);
```

Best regards,
Charles.

**Comment by bi-tm** [comment]
Hello Charles,
i'm glad to hear, that it is working finally.
Of course you may add a hint in the documentation. Just create a pull request and i will merge it.

But wouldn't it be easier to fetch the dataset with the primary key `_id`. Perhaps NeDB allows to put the timestamp into the _id field.
Best Regards
Torsten
