### ISSUE TITLE
Select data to be retreived

### ISSUE THREAD

**Issue by CharlesNepote** [bi-tm/express-nedb-rest#13]
Sometimes we don't want to retrieve all the data we stored in a record.

For example, sometimes we just want to know that a record exist: `$filter=uri $eq http://example.com/thispage $select=uri` should answer:
`{"uri":"http://example.com/thispage"}`

Sometimes we just want a few properties. `$filter=ref $eq 4675 $select=size,price.euro` should answer:
`{"size": "38", "price": { "euros": "152"} }`

We could even have a HTTP 200 without data when we have `$filter=ref $eq 4675 $and size $eq 38 $select=ref`.

That way, there would be less data exchanged between clients and server.

**Comment by bi-tm** [comment]
Good idea, i'am working on it.

**Comment by bi-tm** [comment]
Projection now can be defined with query parameter $select.
Released in v.1.3.0
