### ISSUE TITLE
Problem with missing slashes in URLs

### ISSUE THREAD

**Issue by markhoney** [bi-tm/express-nedb-rest#15]
I've noticed that if a URL doesn't have a trailing slash, the resulting links generated for the base URL don't have a slash between the URL and the name. For example, if I mount my REST api at:

http://localhost:3000/api/rest

the JSON I get back looks like this:

[{"name":"path","link":"http://localhost:3000/api/restpath"},{"name":"otherpath","link":"http://localhost:3000/api/restotherpath"}]

Whereas if I add a trailing slash to my URL:

http://localhost:3000/api/rest/

I get the correct paths to my collections in the JSON:

[{"name":"path","link":"http://localhost:3000/api/rest/path"},{"name":"otherpath","link":"http://localhost:3000/api/rest/otherpath"}]

Looking at the code, the links are generated like this:

"link":  fullUrl(req) + name

It looks simplest to update the fullURL function from this:

function fullUrl(req) {
    return req.protocol + '://' + req.get('host') + req.originalUrl;
}

to this:

function fullUrl(req) {
    return req.protocol + '://' + req.get('host') + req.originalUrl + (req.originalUrl.endsWith('/') ? '' : '/');
}

With the fix in place, the following line (which also uses fullURL) would need to be changed from:

res.append('Location', fullUrl(req) + '/' + doc._id);

to:

res.append('Location', fullUrl(req) + doc._id);

**Comment by bi-tm** [comment]
thank you for your correcions. i merged your pull-request.
regards
Torsten

**Comment by bi-tm** [comment]
correction released in v1.3.0
