### ISSUE TITLE
Post and Put not working

### ISSUE THREAD

**Issue by jmesmoorish** [bi-tm/express-nedb-rest#19]
In this simple script: 
************************************************************************
const express = require('express')
const expressNedbRest = require('express-nedb-rest')
const Datastore = require('nedb')

  // setup express app
  const oApp = express()
  // create  NEDB datastore
  //const nedb = require('nedb');
  
  //const dbUsers = new Datastore({ filename: 'database/users.db', autoload: true })
    
  const dbFruits = new Datastore({ filename: 'database/fruits.db', autoload: true })
  
  // create rest api router and connect it to datastore  
  const restApi = expressNedbRest()
  //restApi.addDatastore('test', dbUsers)
  restApi.addDatastore('fruit', dbFruits)
  
  // setup express server to serve rest service
  oApp.use('/', restApi);
  
  oApp.listen(8080, function () {
      console.log('you may use nedb rest api at port 8080');
  });

  //http://localhost:8080/fruit

************************************************************************
Gets work fine but when I test Puts and Posts with Postman, it only writes the _id field. Any help?

**Comment by bi-tm** [comment]
Hi,
which data did you send to the URL? You have to post a JSON with the properties.
Regards
Torsten

**Comment by jmesmoorish** [comment]
Hi. I send data as is show in this printscreen: 

![imagem](https://user-images.githubusercontent.com/19228199/153208701-08bc80f5-6e3b-4e0a-abbb-bfec25026d7b.png)

**Comment by bi-tm** [comment]
Hi,
please put the data in the request body as JSON string.
![image](https://user-images.githubusercontent.com/1268880/153482192-3c53d2f8-42ed-4fa5-972b-e2d8e306d4ec.png)

**Comment by jmesmoorish** [comment]
Hi! I tried that, but the result was the same... :(

![imagem](https://user-images.githubusercontent.com/19228199/153484261-105509e0-dc70-47cb-8aeb-3a13e69a7633.png)

**Comment by bi-tm** [comment]
Sorry for my wrong example, You have to use the POST method to create an entry. The PUT method is for updating an existing entry. Please have a look in the README (https://github.com/bi-tm/express-nedb-rest#api-schema) and the examples in the little test program.
Regards
Torsten

**Comment by jmesmoorish** [comment]
Problem solved! TY!
