### ISSUE TITLE
index.js line 236 should be "res.status(204).send("deleted entries: "+count);"

### ISSUE THREAD

**Issue by alexluoli** [bi-tm/express-nedb-rest#2]
as title

**Comment by bi-tm** [comment]
Hello,

sorry for responding so late, i was on travel. i will correct the error 
as soon as possible. perhaps you can create a pull request, if you want to?

best regards

Torsten

Am 13.10.2016 um 03:24 schrieb Alex Luo:

**Comment by bi-tm** [comment]
bug is fixed in v1.1.1
